### ISSUE TITLE
전화번호 오류

### ISSUE THREAD

**Issue by alsqkd** [hyunbinseo/civil-defense#10]
분당구 민방위는 031-729-7343 입니다.
인사이동으로 담당자가 바뀌는데 올해 내내 다른 과에 전화문의가 옵니다.
그냥 이 전화번호 고정값으로 하던지 담당자 이름을 연동시키지 마세요. 
업무에 혼선이 생깁니다.

**Comment by hyunbinseo** [comment]
국민재난안전포털에 `031-729-7353`으로 등록되어 있습니다.

<img width="1611" alt="image" src="https://github.com/hyunbinseo/civil-defense/assets/47051820/5b28a3a9-f89e-425b-9404-dc2c038e365c">

민방위 담당자께서 새올행정시스템을 통해 전화번호를 수정하셔야 합니다.

**Comment by hyunbinseo** [comment]
연말에 등록된 교육의 경우 `031-729-3675`로도 등록되어 있는 것을 확인했습니다.

<img width="1075" alt="image" src="https://github.com/hyunbinseo/civil-defense/assets/47051820/e8da8fe0-0daa-4e09-a2fd-4a89272c6736">

새올행정시스템에 등록된 민방위 교육 연락처가 변경되면 답글 남겨주세요. 바로 갱신하겠습니다.

**Comment by hyunbinseo** [comment]
[금주 수요일에 갱신]된 데이터 기준, 등록돼 있는 전화번호는 상기 언급한 두 가지가 전부임을 확인했습니다.

- TEL_NO": "031-729-7353"
- TEL_NO": "031-729-3675"

[금주 수요일에 갱신]: https://github.com/hyunbinseo/civil-defense/blob/89941462ee047dab5ed5fd5b26c68114de78495a/build/6410000/3810000.json

**Comment by alsqkd** [comment]
어떻게 연동이 되는지는 모르겠지만, 저 두개의 번호 모두 새올에 "교육일정을 등록할 당시의 담당자"입니다.교육일정을 등록한 뒤에 다른 부서로 이동했을 때, 일정 등록 당시의 직원의 새로운 부서 번호가 따라간것 같은데교육이 진행되고 있던 상반기, 그리고 지금 하반기 모두 그 담당자가 아니어서 엉뚱한 곳으로 전화가 오고 있네요.상반기에도 업무에 혼선이 생겼고, 왜 그쪽으로 전화가 가는지 모르겠다고 업무 담당자끼리 미안한 마음으로 일했습니다.민방위.kr 사이트에 별도로 문의 전화번호가 없으니 연락이 안 갔겠지만, 비슷한 상황의 공무원들이 많을것으로 생각됩니다.따로 수정이 가능하다면 분당구의 경우 031-729-7343 으로 변경 부탁드립니다.--------- 원본 메일 --------보낸사람 : Hyunbin ***@***.***>받는사람 : hyunbinseo/civil-defense ***@***.***>참조 : alsqkd ***@***.***>, Author ***@***.***>받은날짜 : 2023년 8월 11일(금) 11:59:14 (GMT +09:00)제목 : Re: [hyunbinseo/civil-defense] 전화번호 오류
금주 수요일에 갱신된 데이터 기준, 등록돼 있는 전화번호는 상기 언급한 두 가지가 전부임을 확인했습니다.

TEL_NO": "031-729-7353"
TEL_NO": "031-729-3675"

**Comment by hyunbinseo** [comment]
금일 13시경에 배포될 업데이트에서는 담당자 연락처가 표시되지 않을 예정입니다.

향후에는 [국민재난안전포털 민방위 담당과 연락처](https://www.safekorea.go.kr/idsiSFK/neo/sfk/cs/cvi/cvc/cilcontactList.jsp?menuSeq=51)에 게시된 정보를 활용하겠습니다.

![image](https://github.com/hyunbinseo/civil-defense/assets/47051820/cca8a268-a1eb-4a86-a25d-69609cf983f0)

현재 `031-729-7743`로 등록돼있는데, 이 부분은 수정 가능하실까요?

**Comment by hyunbinseo** [comment]
전화번호가 숨김 처리 되었습니다.

- fixed in 71619d52f6c4d09ec9782fd4021c383e2fa59505
- deployed in cc571015f350760c95909a482e1f25a2253c9e2b
